#!/usr/bin/env python3
from argparse import ArgumentParser
from datetime import date
from pathlib import Path
import string
import random

from edict.ruby import kana_from_anki_furigana, kanji_from_anki_furigana, ruby_from_anki_furigana

START = date(2024, 3, 11)


def gen_challenge(input: Path, output: Path):
    with open(input) as f:
        key, distractor1, distractor2, distractor3, meaning, example, example_translation = f.read().strip().split('\n')

    # Prepare challenge (kanji only)
    challenge = kanji_from_anki_furigana(key)

    # Prepare ruby for key
    key_ruby = ruby_from_anki_furigana(key)

    # Prepare choices
    key_kana = kana_from_anki_furigana(key)
    choice1 = f'<button class="choice" data-correct><div>{key_kana}</div></button>'
    choice2 = f'<button class="choice"><div>{distractor1}</div></button>'
    choice3 = f'<button class="choice"><div>{distractor2}</div></button>'
    choice4 = f'<button class="choice"><div>{distractor3}</div></button>'
    choices = [choice1, choice2, choice3, choice4]
    random.shuffle(choices)
    [choice1, choice2, choice3, choice4] = choices

    # Prepare ruby for example
    example = ruby_from_anki_furigana(example)

    with open('template.html') as f:
        template = f.read()
    html = string.Template(template).substitute(**locals())
    with open(output, 'w') as f:
        f.write(html)


def main() -> None:
    parser = ArgumentParser()
    parser.add_argument('--all', action='store_true')
    args = parser.parse_args()

    dest = Path('public')
    challenges = sorted(Path('challenges').glob('*'))
    if args.all:
        dest.mkdir(exist_ok=True)
        for challenge in challenges:
            output = dest / (challenge.name + '.html')
            print(output)
            gen_challenge(challenge, output)
    else:
        output = dest / 'index.html'
        print(output)
        delta = (date.today() - START).days % len(challenges)
        gen_challenge(challenges[delta], output)


if __name__ == '__main__':
    main()
